import { Investment } from "../types";

export const MARKET_INVESTMENTS: Investment[] = [
  {
    id: "inv-mf-active",
    slug: "mutual-fund-active",
    name: "Actively Managed Mutual Fund",
    aliases: [
      "Active Mutual Funds",
      "Equity Mutual Funds",
      "Debt Mutual Funds",
      "Hybrid Funds",
      "Mutual Fund Schemes",
    ],
    categoryId: "cat-market-funds",
    subcategory: "Active Pooled Vehicles",
    shortDescription:
      "Professionally managed pooled investment vehicle where professional fund managers actively research and select securities to outperform benchmark indices.",
    beginnerExplanation:
      "An active mutual fund is like hiring a team of professional fund managers to invest your money. They collect money from thousands of investors and pick a diversified mix of stocks or bonds aiming to beat the market. You own units representing your share of the overall fund.",
    mechanismSteps: [
      "Investors pool capital into a scheme managed by an Asset Management Company (AMC) registered with SEBI.",
      "A professional Fund Manager and research team build a portfolio of stocks, bonds, or other instruments according to the scheme's mandated investment objective.",
      "The fund manager actively trades, rebalances, and reallocates holdings based on research, valuation metrics, and economic forecasts to outperform a benchmark index.",
      "Total assets minus scheme liabilities determine the Net Asset Value (NAV), computed at the end of every business day.",
      "Investors purchase or redeem units at the applicable daily NAV (subject to cut-off timing and exit loads if applicable).",
    ],

    // Financial facts
    returnInfo: {
      returnType: "market_linked",
      rateDisplay: "Market-linked; varies based on fund performance and underlying asset movements",
      isGuaranteed: false,
      isIllustrative: true,
      description:
        "Returns depend entirely on the capital appreciation and income generated by underlying portfolio securities. Actively managed funds aim for alpha (excess return over the benchmark index) but offer no guaranteed or assured return.",
      benchmark: "Category-dependent (e.g., Nifty 500 TRI for Flexi Cap, Nifty 50 TRI for Large Cap, CRISIL Composite Bond Index for Debt)",
      sourceId: "src-sebi-mf-reg",
    },
    minimumAmount: 100,
    minimumAmountText: "₹100 to ₹500 for SIP; ₹1,000 to ₹5,000 for lump sum (varies by AMC/scheme)",
    maximumAmount: null,
    maximumAmountText: "No statutory maximum limit (individual schemes may occasionally cap inflows during market exuberance)",

    // Risk & Liquidity
    riskLevel: "moderate_to_high",
    riskDescription:
      "Subject to market volatility, portfolio concentration, sector cyclicality, and fund manager risk (the risk that manager choices underperform the benchmark).",
    keyRisks: [
      {
        name: "Market Risk",
        description:
          "Economic downturns, corporate earnings misses, or macroeconomic shifts can depress underlying security prices and scheme NAV.",
      },
      {
        name: "Fund Manager Risk",
        description:
          "Active stock/bond selection decisions can underperform the benchmark index or peer funds over short or extended cycles.",
      },
      {
        name: "Expense Drag",
        description:
          "Higher Total Expense Ratio (TER) of active funds reduces net compounding returns compared to low-cost passive indices.",
      },
      {
        name: "Liquidity & Exit Load",
        description:
          "Redemption within a specified timeframe (typically 7 days to 1 year) may attract an exit load of 0.25% to 1.0%.",
      },
    ],
    liquidityLevel: "high",
    liquidityDescription:
      "Open-ended funds allow redemption on any business day at prevailing NAV, credited to bank account within T+2 (equity) or T+1 (debt/liquid) business days.",
    withdrawalRules: [
      "Redemption requests submitted before cut-off time (typically 3:00 PM) receive that day's NAV.",
      "Exit loads may apply if redeemed before the scheme-specified minimum holding tenure (e.g., 1% for exits within 365 days in equity funds).",
      "Systematic Withdrawal Plans (SWP) allow automated periodic withdrawals for regular cash flow.",
    ],
    lockInPeriod: "None for open-ended schemes (ELSS tax-saving funds carry a mandatory 3-year lock-in)",
    suggestedHorizon: "5+ years for Equity Funds; 3+ years for Hybrid Funds; 1 day to 3 years for Debt Funds (scheme specific)",
    volatilityDescription:
      "Equity funds experience moderate-to-high daily NAV fluctuations; Debt funds experience lower volatility driven primarily by interest rate cycles and credit spreads.",

    // Rules & Administration
    eligibility:
      "Resident Indian individuals, NRIs (subject to AMC/country restrictions such as US/Canada FATCA guidelines), HUFs, minors through guardians, corporates, and trusts.",
    eligibleEntities: [
      "Resident Individuals",
      "Non-Resident Indians (NRIs)",
      "Hindu Undivided Families (HUFs)",
      "Minors (through legal/natural guardian)",
      "Companies & Partnership Firms",
      "Trusts & Societies",
    ],
    regulation: "SEBI (Mutual Funds) Regulations, 1996 and subsequent master circulars",
    administeringAuthority: "Securities and Exchange Board of India (SEBI) / Association of Mutual Funds in India (AMFI)",
    taxationSummary:
      "Equity funds (≥65% domestic equity): Short-term capital gains (<12 months) taxed at 20%; Long-term capital gains (≥12 months) taxed at 12.5% on gains exceeding ₹1.25 lakh per financial year. Debt funds (post April 2023) taxed at applicable income tax slab rates.",
    taxDetails: {
      investmentStage: "No tax deduction on investments, except for ELSS funds eligible under Section 80C (up to ₹1.5 lakh under Old Tax Regime).",
      growthStage: "Capital growth and undistributed gains inside the mutual fund structure are not taxed until units are redeemed.",
      withdrawalStage: "Capital gains realized on redemption are taxed based on asset classification (Equity vs Debt) and holding period under Finance Act 2024 provisions.",
      sectionApplicability: "Sections 112A, 111A, 50AA, and 80C (for ELSS) of the Income Tax Act, 1961",
    },

    // Editorial comparisons
    advantages: [
      "Professional portfolio management with dedicated research and risk management teams.",
      "Instant diversification across 30-70+ securities even with small monthly SIP contributions.",
      "High convenience with automated SIPs, SWPs, STPs, and full digital execution.",
      "Tight regulatory framework under SEBI ensuring scheme transparency, daily NAV disclosures, and portfolio reporting.",
      "Direct plans available with lower expense ratios by eliminating distributor commissions.",
    ],
    limitations: [
      "No assured returns; subject to market volatility and potential drawdown in capital.",
      "Active management fee (Total Expense Ratio) is deducted directly from fund NAV regardless of performance.",
      "Risk of manager underperformance where the fund lags simple, lower-cost index benchmarks over long cycles.",
      "Exit loads and capital gains tax liabilities on switching between schemes or rebalancing.",
    ],
    practicalExample: {
      title: "Disciplined Long-Term SIP in a Diversified Active Equity Fund",
      scenario: "An investor starts a monthly SIP of ₹10,000 in an actively managed flexi-cap equity mutual fund to build a retirement corpus.",
      amountInvested: "₹10,000 per month (₹12,00,000 total invested over 10 years)",
      horizon: "10 Years",
      outcomeExplanation:
        "Through regular monthly rupee cost averaging, the investor buys more units during market dips and fewer during rallies. Over 10 years, compounding and potential alpha generation can build a substantial corpus. Upon redemption, long-term capital gains above ₹1.25 lakh are taxed at 12.5% under prevailing tax rules.",
      disclaimer:
        "Educational illustration only. Mutual fund investments are subject to market risks; past performance does not guarantee future results. NAV and returns fluctuate with market conditions.",
    },
    accessMethods: [
      "Direct AMC Web Portals / Mobile Apps (Direct Plan)",
      "MF Central / MF Utility online platforms",
      "SEBI-registered stockbrokers and discount investment apps",
      "Registered Investment Advisors (RIA) and Mutual Fund Distributors (MFD)",
    ],
    commonMistakes: [
      "Investing in regular plans instead of direct plans when investing independently, sacrificing compounding to ongoing distributor commissions.",
      "Chasing last year's top-performing fund category or scheme rather than adhering to an asset allocation plan.",
      "Stopping SIPs or panicking during market corrections when unit acquisition prices are most favorable.",
      "Over-diversifying by holding 15-20 overlapping mutual fund schemes within the same asset class.",
    ],
    faqs: [
      {
        question: "What is the difference between Direct and Regular mutual fund plans?",
        answer:
          "Direct plans are bought directly from the AMC without distributor commission, resulting in a lower Total Expense Ratio (TER) and higher net NAV compounding over time. Regular plans include an ongoing distributor commission built into the annual expense ratio.",
      },
      {
        question: "Can I lose money in an active mutual fund?",
        answer:
          "Yes. Mutual funds are market-linked instruments with no capital guarantee. In the short to medium term, negative market cycles can lead to NAV declines below your invested amount.",
      },
      {
        question: "What is an Exit Load in mutual funds?",
        answer:
          "An exit load is a fractional percentage fee charged by the mutual fund scheme if you redeem or switch units before a predefined holding duration (for instance, 1% if redeemed within 1 year). It is deducted from the redemption proceeds.",
      },
      {
        question: "How does SIP (Systematic Investment Plan) work?",
        answer:
          "A SIP automatically debits a fixed sum from your bank account on a chosen date each month (or week) to purchase scheme units at that day's NAV, averaging out purchase costs across market highs and lows.",
      },
    ],
    relatedInvestmentSlugs: ["index-fund", "exchange-traded-fund", "direct-stocks"],

    // Metadata & Sources
    sourceIds: ["src-sebi-mf-reg", "src-amfi-data", "src-incometax-act"],
    status: "draft",
    lastVerifiedAt: "",
    completenessScore: 85,
    editorialNotes: "Seed content covering active mutual funds across equity and hybrid categories in India.",
  },

  {
    id: "inv-index-fund",
    slug: "index-fund",
    name: "Index Mutual Fund (Passive)",
    aliases: [
      "Passive Mutual Funds",
      "Nifty 50 Index Fund",
      "Sensex Index Fund",
      "Broad Market Index Funds",
    ],
    categoryId: "cat-market-funds",
    subcategory: "Passive Pooled Vehicles",
    shortDescription:
      "Low-cost passively managed mutual fund designed to replicate the exact portfolio composition and returns of a benchmark stock index.",
    beginnerExplanation:
      "An index fund automatically copies a major market index like the Nifty 50 or Sensex, buying the exact same stocks in the same proportions. There is no fund manager trying to guess which stocks will win, which keeps costs extremely low. As the overall market grows over time, your investment grows along with it.",
    mechanismSteps: [
      "The Asset Management Company (AMC) selects a target benchmark market index (e.g., Nifty 50, BSE Sensex, Nifty Next 50, or Nifty Midcap 150).",
      "The fund manager deploys investor capital to purchase all constituent securities in the exact weights dictated by the underlying index rules.",
      "When the index provider periodically reconstitutes or reweights the index (typically semi-annually), the fund mechanically rebalances its holdings to match.",
      "Daily NAV is published based on the collective market value of the underlying basket minus an ultra-low expense ratio.",
      "Investors buy and redeem units directly with the AMC at the end-of-day NAV without needing a Demat or trading account.",
    ],

    // Financial facts
    returnInfo: {
      returnType: "market_linked",
      rateDisplay: "Market-linked; tracks the benchmark index returns minus the expense ratio and tracking error",
      isGuaranteed: false,
      isIllustrative: true,
      description:
        "Returns mirror the performance of the underlying benchmark index (e.g. Nifty 50 TRI). Index funds do not attempt to beat the market, but aim to match index performance with minimal tracking error.",
      benchmark: "Underlying Target Index (e.g., Nifty 50 TRI, BSE Sensex TRI, Nifty Midcap 150 TRI)",
      sourceId: "src-sebi-mf-reg",
    },
    minimumAmount: 100,
    minimumAmountText: "₹100 to ₹500 for SIP; ₹1,000 for lump sum (varies by AMC)",
    maximumAmount: null,
    maximumAmountText: "No statutory maximum limit",

    // Risk & Liquidity
    riskLevel: "moderate_to_high",
    riskDescription:
      "Reflects the full market volatility of the underlying index. Large-cap index funds carry moderate-to-high risk, while mid/small-cap index funds carry high risk.",
    keyRisks: [
      {
        name: "Market Risk",
        description:
          "The fund will fall when the broader benchmark index falls; passive managers do not hold cash or hedge during market downturns.",
      },
      {
        name: "Tracking Error",
        description:
          "Discrepancy between the fund's NAV return and the actual Total Returns Index due to cash drag, transaction fees, and corporate action timing.",
      },
      {
        name: "No Downside Protection",
        description:
          "Unlike active funds that might hold cash or rotate to defensive sectors, index funds must stay 95-100% invested in index constituents at all times.",
      },
      {
        name: "Index Concentration",
        description:
          "Top 5-10 stocks in market-cap weighted indices (like Nifty 50) can represent 40-50% of the entire portfolio.",
      },
    ],
    liquidityLevel: "high",
    liquidityDescription:
      "High liquidity through direct AMC redemption on business days at daily NAV. Settlement typically T+2 business days.",
    withdrawalRules: [
      "Redeemable on any business day at prevailing NAV directly through the AMC or investment platforms.",
      "Most index funds carry minimal or zero exit loads after 0 to 7 days.",
      "SIP, SWP, and STP facilities available identical to standard mutual funds.",
    ],
    lockInPeriod: "None (open-ended)",
    suggestedHorizon: "5+ to 7+ years for broad market equity index funds",
    volatilityDescription:
      "Matches the day-to-day volatility and drawdowns of the underlying equity market index.",

    // Rules & Administration
    eligibility:
      "Resident Indian individuals, NRIs, HUFs, minors through guardians, corporates, and institutions.",
    eligibleEntities: [
      "Resident Individuals",
      "Non-Resident Indians (NRIs)",
      "Hindu Undivided Families (HUFs)",
      "Minors (through legal guardian)",
      "Corporate Entities & Trusts",
    ],
    regulation: "SEBI (Mutual Funds) Regulations, 1996 - Passive Fund categorization norms",
    administeringAuthority: "Securities and Exchange Board of India (SEBI) / AMFI",
    taxationSummary:
      "Equity Index Funds (≥65% domestic equity): STCG (<12 months) at 20%; LTCG (≥12 months) at 12.5% for gains above ₹1.25 lakh per financial year (as per Finance Act 2024).",
    taxDetails: {
      investmentStage: "No tax deduction on investments (unless specifically an index-based ELSS eligible under 80C in old regime).",
      growthStage: "No tax on unrealized index gains or internal rebalancing within the mutual fund pool.",
      withdrawalStage: "Capital gains tax applied upon redemption based on equity fund holding period guidelines.",
      sectionApplicability: "Sections 112A and 111A of the Income Tax Act, 1961",
    },

    // Editorial comparisons
    advantages: [
      "Significantly lower expense ratios (often 0.10% to 0.40% for Direct plans) compared to active funds.",
      "Eliminates fund manager bias, style drift, and individual stock-picking risk.",
      "Full transparency of holdings since portfolio composition is publicly defined by index constituents.",
      "Can be bought via simple automated SIPs without requiring a Demat or trading account.",
      "Historically proven to beat a majority of actively managed large-cap funds over 10+ year horizons after fees.",
    ],
    limitations: [
      "Guaranteed never to beat the benchmark index (returns will always equal index return minus TER and tracking error).",
      "Maintains 100% equity exposure during severe bear markets with zero defensive hedging or cash calls.",
      "Market-cap weighting can lead to high concentration in a few heavy-weight stocks or outperforming sectors.",
      "Tracking errors can reduce realized investor returns if the AMC manages cash inflows and corporate actions inefficiently.",
    ],
    practicalExample: {
      title: "Building Core Wealth with a Nifty 50 Index Fund SIP",
      scenario: "An investor wanting broad Indian corporate exposure invests ₹15,000 per month in a Nifty 50 Direct Index Fund for long-term financial independence.",
      amountInvested: "₹15,000 per month (₹18,00,000 over 10 years)",
      horizon: "10 Years",
      outcomeExplanation:
        "The investor automatically owns a slice of India's top 50 blue-chip companies with ultra-low annual fees. When dividends are reinvested (Total Return Index), compounding works efficiently without manager risk. Upon withdrawal after 10 years, gains above the ₹1.25 lakh exemption are subject to 12.5% LTCG tax.",
      disclaimer:
        "Educational illustration only. Index fund performance is linked to stock market indices and is subject to market risks. Past index returns are not an indicator of future performance.",
    },
    accessMethods: [
      "Direct AMC websites / Mobile apps",
      "Mutual fund aggregation apps and MF Central",
      "Online stockbrokers and demat/non-demat mutual fund platforms",
    ],
    commonMistakes: [
      "Selecting an index fund scheme with high tracking error or high expense ratio when identical alternatives exist at lower cost.",
      "Expecting the fund to protect capital during market downturns.",
      "Stopping monthly SIPs during market crashes instead of continuing passive accumulation at lower valuations.",
      "Confusing Index Mutual Funds with ETFs (Index Funds do not require a Demat account or intraday order execution).",
    ],
    faqs: [
      {
        question: "What is tracking error in an index fund?",
        answer:
          "Tracking error measures how closely the index fund's returns replicate the returns of its target benchmark index. Lower tracking error means the fund manager is replicating the index more accurately with minimal deviation.",
      },
      {
        question: "Do I need a Demat account to invest in index funds?",
        answer:
          "No. Unlike ETFs, index mutual funds can be bought and redeemed directly through AMCs or mutual fund platforms without a Demat or trading account.",
      },
      {
        question: "Why do many investors prefer index funds over active mutual funds?",
        answer:
          "Index funds feature much lower management fees, avoid the risk of poor stock picking by active managers, and offer complete transparency by tracking well-known market benchmarks.",
      },
      {
        question: "Are dividends paid out in index funds?",
        answer:
          "In Growth plans, dividends received from underlying stocks are automatically reinvested into the fund (replicated as a Total Return Index / TRI), increasing the NAV over time.",
      },
    ],
    relatedInvestmentSlugs: ["exchange-traded-fund", "mutual-fund-active", "direct-stocks"],

    // Metadata & Sources
    sourceIds: ["src-sebi-mf-reg", "src-amfi-data", "src-incometax-act"],
    status: "draft",
    lastVerifiedAt: "",
    completenessScore: 85,
    editorialNotes: "Comprehensive overview of passive index mutual funds in the Indian market.",
  },

  {
    id: "inv-exchange-traded-fund",
    slug: "exchange-traded-fund",
    name: "Exchange Traded Fund (ETF)",
    aliases: [
      "ETFs",
      "Stock ETFs",
      "Gold ETF",
      "Nifty BeES",
      "Debt ETF",
      "Liquid ETF",
      "Bharat 22 ETF",
    ],
    categoryId: "cat-market-funds",
    subcategory: "Exchange Traded Passive Products",
    shortDescription:
      "Market-linked passive fund traded on stock exchanges throughout the trading day at real-time market prices.",
    beginnerExplanation:
      "An ETF is a basket of stocks, bonds, or commodities like gold that you can buy and sell on the stock exchange just like a single company's share. Because it trades live during market hours, you know the exact price at the moment you buy or sell. It offers instant diversification with very low management fees.",
    mechanismSteps: [
      "An AMC creates an ETF tracking an index, commodity (like Gold/Silver), or bond basket, and issues creation units to Authorized Participants (APs).",
      "ETF units are listed on the National Stock Exchange (NSE) and Bombay Stock Exchange (BSE).",
      "Retail investors place buy or sell limit/market orders through their stockbroker during normal market hours (9:15 AM to 3:30 PM IST).",
      "Authorized Participants engage in continuous market making, creating or redeeming large baskets with the AMC to keep the market price close to the intraday Indicative Net Asset Value (iNAV).",
      "Transactions settle on the exchange settlement cycle (T+1 rolling settlement), with units credited or debited in the investor's Demat account.",
    ],

    // Financial facts
    returnInfo: {
      returnType: "market_linked",
      rateDisplay: "Market-linked; tracks underlying index/asset price live on stock exchanges",
      isGuaranteed: false,
      isIllustrative: true,
      description:
        "Returns track the price movements of the underlying index, basket, or commodity (such as physical gold bullion). Returns are earned through exchange price appreciation and dividend distributions.",
      benchmark: "Target Benchmark Index or Spot Commodity Price (e.g. Nifty 50, Nifty Bank, Domestic Spot Gold Price)",
      sourceId: "src-sebi-mf-reg",
    },
    minimumAmount: 1,
    minimumAmountText: "Price of 1 unit on the stock exchange (can be as low as ₹20 to ₹500 depending on the ETF)",
    maximumAmount: null,
    maximumAmountText: "No statutory maximum limit",

    // Risk & Liquidity
    riskLevel: "moderate_to_high",
    riskDescription:
      "Varies with the underlying asset class (Equity ETFs carry moderate-to-high market risk; Gold ETFs carry commodity price risk; Debt ETFs carry interest rate risk) plus intraday exchange liquidity risk.",
    keyRisks: [
      {
        name: "Market & Asset Risk",
        description:
          "The underlying basket of stocks, bonds, or gold fluctuates with real-time global and domestic market forces.",
      },
      {
        name: "Liquidity & Spread Risk",
        description:
          "Low trading volume on certain niche ETFs can cause a wide bid-ask spread and significant deviation between market price and actual iNAV.",
      },
      {
        name: "Tracking Error & Premium/Discount",
        description:
          "Units may trade at a persistent premium or discount to fair NAV if authorized participant market-making is inefficient.",
      },
      {
        name: "Brokerage & Demat Friction",
        description:
          "Requires a trading/Demat account; brokerage, STT, exchange turnover fees, and depository charges apply to every trade.",
      },
    ],
    liquidityLevel: "high",
    liquidityDescription:
      "Intraday liquidity on stock exchanges during trading hours (9:15 AM - 3:30 PM IST), subject to trading volume on the specific ETF ticker.",
    withdrawalRules: [
      "Units can be sold instantly on the stock exchange at prevailing live bid prices during market hours.",
      "Funds from sale are credited per exchange T+1 settlement cycles (up to 80% available immediately on trade day for new trades in India).",
      "No exit load charged by AMC for exchange trades, though standard brokerage and statutory taxes apply.",
    ],
    lockInPeriod: "None",
    suggestedHorizon: "3+ to 5+ years for Equity ETFs; 1 to 3+ years for Gold & Debt ETFs",
    volatilityDescription:
      "Trades tick-by-tick during market hours matching the live volatility of underlying stocks, commodities, or bonds.",

    // Rules & Administration
    eligibility:
      "Individuals holding a valid Demat and Trading account with a SEBI-registered stockbroker (Residents, NRIs, HUFs, Corporates, Institutional Investors).",
    eligibleEntities: [
      "Resident Individuals",
      "Non-Resident Indians (NRIs)",
      "Hindu Undivided Families (HUFs)",
      "Corporate Bodies & LLPs",
      "Qualified Institutional Buyers (QIBs)",
    ],
    regulation: "SEBI (Mutual Funds) Regulations, 1996 and SEBI Master Circular for ETFs / Index Funds",
    administeringAuthority: "Securities and Exchange Board of India (SEBI) / Stock Exchanges (NSE & BSE)",
    taxationSummary:
      "Equity ETFs: STCG (<12m) taxed at 20%; LTCG (≥12m) taxed at 12.5% above ₹1.25 lakh threshold. Gold & Non-Equity ETFs: Taxed per Finance Act 2024 (LTCG at 12.5% if held >24 months, STCG at slab rates if held ≤24 months).",
    taxDetails: {
      investmentStage: "No tax deduction on purchase.",
      growthStage: "No interim taxation until units are sold on the exchange.",
      withdrawalStage: "Capital gains tax applies on exchange sale profits based on asset type and holding period.",
      sectionApplicability: "Sections 112A, 111A, and 112 of the Income Tax Act, 1961",
    },

    // Editorial comparisons
    advantages: [
      "Real-time intraday trading flexibility allowing limit orders, stop-loss orders, and immediate execution during market hours.",
      "Ultra-low management expense ratios compared to actively managed mutual funds.",
      "No minimum SIP commitment; can buy as little as 1 single unit on the exchange.",
      "Excellent vehicle for commodity exposure like physical 99.5% purity gold without storage or making charge hassles.",
      "High portfolio transparency with real-time indicative NAV (iNAV) published on exchange feeds every few seconds.",
    ],
    limitations: [
      "Requires an active Demat and trading account with ongoing DP/account maintenance fees.",
      "Illiquid ETFs can suffer from wide bid-ask spreads, forcing retail investors to buy at a premium or sell at a discount.",
      "Automating monthly investments can be less seamless than standard mutual fund auto-debit SIPs on some broker platforms.",
      "Transaction costs such as brokerage, Securities Transaction Tax (STT), stamp duty, and exchange turnover charges apply.",
    ],
    practicalExample: {
      title: "Allocating to Gold and Equities via Exchange Traded Funds",
      scenario: "An investor allocates ₹50,000 to purchase 100 units of a Nifty 50 ETF and 50 units of a Gold ETF during an intraday market dip using limit orders.",
      amountInvested: "₹50,000 total lump sum",
      horizon: "5 Years",
      outcomeExplanation:
        "The investor locks in real-time execution prices. The equity ETF captures broader Indian economic growth while the Gold ETF provides an inflation hedge. Holding in demat format eliminates locker charges and purity testing concerns. When sold after 5 years, long-term capital gains tax applies per applicable asset rules.",
      disclaimer:
        "Educational illustration only. ETF market prices fluctuate intraday based on demand, supply, and underlying asset valuation. Past market performance is not indicative of future returns.",
    },
    accessMethods: [
      "Online stock trading platforms and discount broker apps (e.g., Zerodha, Groww, AngelOne, Upstox)",
      "Full-service broker trading desks",
      "Direct large-block creation/redemption with AMC for institutional Authorized Participants",
    ],
    commonMistakes: [
      "Placing market orders on low-volume ETFs, resulting in unfavorable execution prices far from the true iNAV.",
      "Failing to check the indicative NAV (iNAV) before executing trades on the exchange.",
      "Frequent speculative intraday day-trading rather than long-term strategic asset allocation.",
      "Ignoring trading friction costs and brokerage fees on very small frequent transactions.",
    ],
    faqs: [
      {
        question: "How does an ETF differ from an Index Mutual Fund?",
        answer:
          "While both track an index, ETFs are traded on stock exchanges at fluctuating prices throughout the day and require a Demat/trading account. Index mutual funds are bought and redeemed directly with the AMC at a single end-of-day NAV without requiring a Demat account.",
      },
      {
        question: "What is iNAV in ETFs?",
        answer:
          "Indicative NAV (iNAV) is the real-time estimated fair value of an ETF unit calculated and published on exchange tickers every few seconds based on live prices of underlying constituents.",
      },
      {
        question: "Can I do a monthly SIP in an ETF?",
        answer:
          "Yes, many modern Indian stockbrokers offer 'Stock SIP' or 'ETF SIP' features that automatically place market or limit orders on scheduled dates, though it requires sufficient cash balance in your trading account.",
      },
      {
        question: "Why do some ETFs trade at prices different from their NAV?",
        answer:
          "Deviations happen when trading liquidity is thin or market makers (Authorized Participants) face friction in arbitrage. Highly liquid ETFs typically trade very close to their iNAV.",
      },
    ],
    relatedInvestmentSlugs: ["index-fund", "mutual-fund-active", "direct-stocks"],

    // Metadata & Sources
    sourceIds: ["src-sebi-mf-reg", "src-amfi-data", "src-incometax-act"],
    status: "draft",
    lastVerifiedAt: "",
    completenessScore: 85,
    editorialNotes: "Covers equity, gold, and debt ETFs traded on Indian exchanges.",
  },

  {
    id: "inv-direct-stocks",
    slug: "direct-stocks",
    name: "Direct Listed Equity Shares",
    aliases: [
      "Direct Equities",
      "Stock Market",
      "Shares",
      "BSE / NSE Stocks",
      "Cash Equities",
    ],
    categoryId: "cat-equity",
    subcategory: "Direct Company Ownership",
    shortDescription:
      "Direct fractional equity ownership in publicly listed Indian enterprises traded on the National Stock Exchange (NSE) and Bombay Stock Exchange (BSE).",
    beginnerExplanation:
      "Buying direct stocks means purchasing fractional ownership in a specific company listed on the stock market. If the business grows profits and expands, the share price rises and you may receive dividends. However, if the company struggles or fails, you can lose a significant portion or all of your invested money.",
    mechanismSteps: [
      "Companies list their equity shares on stock exchanges (NSE/BSE) via an IPO or direct listing under SEBI guidelines.",
      "Investors open a trading and Demat account with a SEBI-registered stockbroker and link their bank account.",
      "Investors analyze company fundamentals, corporate governance, financial statements, and valuation before placing buy orders.",
      "Orders are matched electronically on exchange order books, and shares are settled into the investor's Demat account on a T+1 settlement cycle.",
      "Shareholders receive voting rights, annual reports, and direct corporate actions such as dividend payouts, stock splits, and bonus shares.",
    ],

    // Financial facts
    returnInfo: {
      returnType: "market_linked",
      rateDisplay: "Market-linked; capital gains from share price appreciation plus dividend yields",
      isGuaranteed: false,
      isIllustrative: true,
      description:
        "Returns are non-guaranteed and determined entirely by business performance, industry economics, company earnings, and market valuation multiples over time.",
      benchmark: "BSE Sensex, Nifty 50, Nifty 500, or sector-specific benchmarks",
      sourceId: "src-sebi-mf-reg",
    },
    minimumAmount: 1,
    minimumAmountText: "Price of 1 individual share (ranges from less than ₹10 to over ₹1,00,000 depending on the company)",
    maximumAmount: null,
    maximumAmountText: "No legal upper limit for retail investors (substantial acquisition norms apply above 5% ownership under SEBI SAST regulations)",

    // Risk & Liquidity
    riskLevel: "very_high",
    riskDescription:
      "Direct business, operational, management, governance, and market valuation risks. Unlike diversified funds, individual stocks carry the risk of total capital loss.",
    keyRisks: [
      {
        name: "Company-Specific & Business Risk",
        description:
          "Disruptions, poor management decisions, competitive pressure, or corporate fraud can destroy shareholder value.",
      },
      {
        name: "Price & Valuation Volatility",
        description:
          "Stock prices can swing sharply due to quarterly earnings surprises, macro interest rate shifts, and market sentiment.",
      },
      {
        name: "Concentration Risk",
        description:
          "Holding too few stocks leaves the investor unprotected if one or two major holdings experience catastrophic declines.",
      },
      {
        name: "Emotional & Behavioral Risk",
        description:
          "Panic selling at market bottoms or FOMO buying at market tops severely damages long-term investor returns.",
      },
    ],
    liquidityLevel: "high",
    liquidityDescription:
      "High liquidity for large and mid-cap stocks during market hours; small-cap and micro-cap stocks may suffer from low volumes or upper/lower circuit limits.",
    withdrawalRules: [
      "Shares can be sold on any trading day during market hours (9:15 AM to 3:30 PM IST).",
      "Proceeds settle on a T+1 basis (credited to your brokerage trading ledger and transferable to your bank account).",
      "Circuit breakers (2%, 5%, 10%, or 20%) can temporarily freeze trading if the stock experiences extreme price moves.",
    ],
    lockInPeriod: "None (for normal secondary market cash equity purchases)",
    suggestedHorizon: "5+ to 10+ years for compounding wealth through quality businesses",
    volatilityDescription:
      "High to very high intraday and multi-year price fluctuations driven by news, quarterly financial results, and global market trends.",

    // Rules & Administration
    eligibility:
      "Resident Indian individuals, NRIs (under Portfolio Investment Scheme / PIS or Non-PIS route), HUFs, Corporate bodies, Registered Foreign Portfolio Investors (FPIs).",
    eligibleEntities: [
      "Resident Individuals",
      "Non-Resident Indians (NRIs)",
      "Hindu Undivided Families (HUFs)",
      "Corporate Entities & LLPs",
      "Trusts (subject to trust deed provisions)",
    ],
    regulation: "Securities and Exchange Board of India (SEBI) Act, 1992 and Companies Act, 2013",
    administeringAuthority: "Securities and Exchange Board of India (SEBI) / NSE / BSE",
    taxationSummary:
      "Listed Equity Shares: Short-Term Capital Gains (<12 months) taxed at 20% under Section 111A. Long-Term Capital Gains (≥12 months) taxed at 12.5% under Section 112A for gains exceeding ₹1.25 lakh per financial year. Dividends are taxed at normal income tax slab rates.",
    taxDetails: {
      investmentStage: "No tax deduction on buying shares; Securities Transaction Tax (STT) and stamp duty levied on purchase transaction.",
      growthStage: "Unrealized capital gains are not taxed while shares are held in Demat.",
      withdrawalStage: "STCG (20%) or LTCG (12.5% above ₹1.25 lakh threshold) applied on net realized profits upon selling.",
      sectionApplicability: "Sections 111A, 112A, and 56(2) (for dividends) of the Income Tax Act, 1961",
    },

    // Editorial comparisons
    advantages: [
      "Direct ownership in thriving businesses with uncapped upside potential from earnings compounding.",
      "Direct receipt of dividends into bank accounts and participation in corporate actions (bonus, splits, rights issues).",
      "No recurring fund management fee or asset management expense ratio deducted from your capital.",
      "Complete control over portfolio construction, stock selection, and timing of buys/sells.",
      "Voting rights allowing direct participation in shareholder resolutions and company governance.",
    ],
    limitations: [
      "Requires extensive time, financial literacy, accounting knowledge, and analytical effort to research companies.",
      "Lack of diversification in small portfolios creates high risk of permanent capital loss.",
      "Subject to severe emotional traps like panic selling during market corrections or chasing speculative penny stocks.",
      "Corporate governance risks and accounting irregularities can lead to sudden collapse in share value.",
    ],
    practicalExample: {
      title: "Long-Term Ownership in a Growing Consumer Enterprise",
      scenario: "An investor researches an established Indian FMCG company, buying 100 shares at ₹500 each (₹50,000 invested) with an 8-year holding thesis.",
      amountInvested: "₹50,000",
      horizon: "8 Years",
      outcomeExplanation:
        "Over 8 years, the company expands revenues, increases dividends, and experiences price appreciation. The investor collects yearly dividend payouts directly into their bank account. When sold after 8 years, profits exceeding the annual ₹1.25 lakh cumulative LTCG exemption are taxed at 12.5%.",
      disclaimer:
        "Educational illustration only. Individual stock prices are highly volatile and can result in total loss of invested capital. Not an endorsement of any specific stock.",
    },
    accessMethods: [
      "SEBI-registered stockbrokers (Discount brokers and Full-service brokers)",
      "Online trading web portals and mobile applications",
      "Institutional and PMS brokerage desks",
    ],
    commonMistakes: [
      "Investing based on social media tips, WhatsApp forwards, or speculative rumors without fundamental analysis.",
      "Allocating significant capital to penny stocks hoping for fast multi-bagger returns.",
      "Failing to diversify across sectors and holding an overly concentrated portfolio of high-beta stocks.",
      "Treating investing as short-term gambling rather than long-term business ownership.",
      "Averaging down on structurally declining or fraudulent businesses just because the share price has dropped.",
    ],
    faqs: [
      {
        question: "What is the difference between investing in stocks and investing in mutual funds?",
        answer:
          "In direct stocks, you select and manage individual company shares yourself with zero management fees, taking on individual business risk. In mutual funds, a professional fund manager manages a diversified basket of dozens of stocks for an annual expense ratio fee.",
      },
      {
        question: "What happens if a listed company goes bankrupt?",
        answer:
          "Equity shareholders are the residual owners of the company. In liquidation or bankruptcy under the Insolvency and Bankruptcy Code (IBC), debt holders and creditors are paid first, and equity shareholders typically face a 100% loss of their investment.",
      },
      {
        question: "How are dividends taxed on direct stocks in India?",
        answer:
          "Dividends received from listed Indian companies are added to your total annual taxable income and taxed at your applicable income tax slab rate. TDS (Tax Deducted at Source) at 10% is deducted by the company if annual dividends exceed ₹5,000.",
      },
      {
        question: "What are circuit breakers in stock trading?",
        answer:
          "Circuit limits are maximum percentage price movement limits (e.g., 5%, 10%, 20%) set by stock exchanges to prevent excessive panic or speculative manipulation in a single trading session.",
      },
    ],
    relatedInvestmentSlugs: ["initial-public-offering", "index-fund", "mutual-fund-active", "exchange-traded-fund"],

    // Metadata & Sources
    sourceIds: ["src-sebi-mf-reg", "src-incometax-act"],
    status: "draft",
    lastVerifiedAt: "",
    completenessScore: 85,
    editorialNotes: "Detailed overview of direct equity shareholding on BSE/NSE.",
  },

  {
    id: "inv-initial-public-offering",
    slug: "initial-public-offering",
    name: "Initial Public Offering (IPO)",
    aliases: [
      "IPO",
      "Public Issue",
      "Primary Market Equity",
      "Mainboard IPO",
      "SME IPO",
    ],
    categoryId: "cat-equity",
    subcategory: "Primary Market Offerings",
    shortDescription:
      "Primary market process where an unlisted private company issues fresh shares or offers existing shares for sale (OFS) to the public and lists on stock exchanges.",
    beginnerExplanation:
      "An IPO is when a private company sells its shares to the general public for the very first time to raise capital and get listed on the stock exchange. Retail investors apply for shares within a specified price band before the stock starts trading publicly. If allocated shares, you can choose to hold them for long-term growth or sell them on listing day.",
    mechanismSteps: [
      "The issuing company files a Draft Red Herring Prospectus (DRHP) with SEBI and merchant bankers to detail its financials, business model, and capital utilization plans.",
      "Upon regulatory approval, the company announces the public issue dates, price band, and minimum lot size.",
      "Retail investors submit IPO bids via ASBA (Application Supported by Blocked Amount) through their bank or UPI-linked broker interface.",
      "Funds remain blocked in the investor's bank account until allotment is finalized; if oversubscribed, lottery-based allotment rules determine allocation.",
      "Allotted shares are credited to the investor's Demat account, unallocated funds are unblocked, and shares commence public secondary market trading on listing day.",
    ],

    // Financial facts
    returnInfo: {
      returnType: "market_linked",
      rateDisplay: "Market-linked; listing gains and long-term share price performance post-listing",
      isGuaranteed: false,
      isIllustrative: true,
      description:
        "Returns depend on listing day market sentiment (listing gains or discounts) and subsequent long-term corporate earnings performance. There is zero guarantee of positive listing returns or share allotment.",
      benchmark: "BSE IPO Index / NSE Nifty 500",
      sourceId: "src-sebi-mf-reg",
    },
    minimumAmount: 14000,
    minimumAmountText: "₹14,000 to ₹15,000 per lot for Mainboard IPOs (SME IPOs require ₹1,00,000 to ₹1,50,000+ per lot)",
    maximumAmount: 200000,
    maximumAmountText: "₹2,00,000 for Retail Individual Investor (RII) quota (bids above ₹2 Lakh fall into High Net-Worth Individual / HNI quota)",

    // Risk & Liquidity
    riskLevel: "very_high",
    riskDescription:
      "High valuation uncertainty, limited public market financial operating history, grey market premium (GMP) speculation, and post-listing price volatility.",
    keyRisks: [
      {
        name: "Valuation & Overpricing Risk",
        description:
          "Promoters and pre-IPO investors may price the public issue at aggressive multiples, leaving little upside margin of safety for retail buyers.",
      },
      {
        name: "Listing Loss Risk",
        description:
          "If market sentiment deteriorates or institutional interest is weak, shares can list at a steep discount to the issue price.",
      },
      {
        name: "Allotment Uncertainty",
        description:
          "Heavily oversubscribed IPOs use computerized lottery draws, meaning investors often receive zero shares in attractive issues.",
      },
      {
        name: "Anchor Lock-In Expiry",
        description:
          "Shares often face sharp selling pressure when mandatory anchor investor lock-in periods (30 and 90 days) expire post-listing.",
      },
    ],
    liquidityLevel: "high",
    liquidityDescription:
      "Capital is blocked in bank account during the 3 to 5 day bidding and allotment window. Once listed, shares can be sold freely during exchange trading hours.",
    withdrawalRules: [
      "Investors can modify or cancel IPO bids anytime before the issue closes on the final bidding day.",
      "Blocked funds under ASBA are unblocked immediately if no shares are allotted.",
      "Once shares are allotted and listed on the exchange, they follow standard cash equity trading rules.",
    ],
    lockInPeriod: "None for retail public applicants (Anchor investors face 30-day and 90-day lock-in periods on portions of their allocation)",
    suggestedHorizon: "Listing day (for listing gain strategies) or 3+ to 7+ years (for fundamentally strong long-term compounders)",
    volatilityDescription:
      "Extreme price swings and high turnover on listing day and during initial quarterly reporting cycles.",

    // Rules & Administration
    eligibility:
      "Resident Indian individuals, HUFs, NRIs (subject to FEMA guidelines), institutional buyers, and high net-worth individuals with an active PAN and Demat account.",
    eligibleEntities: [
      "Retail Individual Investors (RII)",
      "Non-Institutional Investors (NII / HNI)",
      "Qualified Institutional Buyers (QIB)",
      "Anchor Investors",
      "Eligible Employees / Shareholders",
    ],
    regulation: "SEBI (Issue of Capital and Disclosure Requirements) Regulations, 2018 (ICDR)",
    administeringAuthority: "Securities and Exchange Board of India (SEBI) / Stock Exchanges / Registrar and Transfer Agents (RTA)",
    taxationSummary:
      "Same as listed equities post-listing: If sold on listing day or within 12 months, Short-Term Capital Gains (STCG) taxed at 20%. If held for 12+ months, Long-Term Capital Gains (LTCG) taxed at 12.5% above ₹1.25 lakh per financial year.",
    taxDetails: {
      investmentStage: "Funds blocked via ASBA earn normal savings bank interest until allotment and debit.",
      growthStage: "No tax until shares are sold on the secondary market.",
      withdrawalStage: "STCG (20%) on quick listing-day flips; LTCG (12.5% over ₹1.25L) on long-term holdings.",
      sectionApplicability: "Sections 111A and 112A of the Income Tax Act, 1961",
    },

    // Editorial comparisons
    advantages: [
      "Opportunity to participate in emerging companies and sector leaders at their public inception.",
      "Potential for rapid listing day gains if the issue is heavily demanded and priced attractively.",
      "Seamless application process via UPI ASBA where funds never leave your bank account unless shares are allotted.",
      "SEBI mandates extensive disclosures in the Red Herring Prospectus (RHP) regarding business risks and use of proceeds.",
      "Transparent retail reservation quota (typically 35% of the total issue for mainboard issues).",
    ],
    limitations: [
      "Low probability of allotment in popular, high-quality IPOs due to severe oversubscription.",
      "Many IPOs are structured primarily as 'Offer for Sale' (OFS) where money goes to exiting private equity investors rather than funding company growth.",
      "Misleading hype driven by unregulated Grey Market Premium (GMP) data.",
      "High post-listing volatility can lead to deep losses if the business fails to deliver on growth projections.",
    ],
    practicalExample: {
      title: "Applying for a Mainboard Tech IPO via UPI ASBA",
      scenario: "A retail investor applies for 1 lot (30 shares at ₹500/share = ₹15,000) of an expanding Indian enterprise via their banking app UPI ASBA mandate.",
      amountInvested: "₹15,000 blocked in bank account",
      horizon: "3-5 days to allotment; 3+ years for long-term holding",
      outcomeExplanation:
        "₹15,000 is blocked in the investor's savings account while earning savings interest. Upon successful allotment, the amount is debited and 30 shares are credited to the Demat account. If the stock lists at ₹600, the investor enjoys a ₹3,000 listing gain. If sold immediately, the gain is taxed at 20% STCG.",
      disclaimer:
        "Educational illustration only. IPO applications do not guarantee share allotment or positive listing returns. Past IPO trends do not assure future outcomes.",
    },
    accessMethods: [
      "UPI-based ASBA through stockbroking mobile applications",
      "Internet banking net-banking ASBA portal",
      "Physical syndicate member bidding forms at designated collection centers",
    ],
    commonMistakes: [
      "Applying blindly based solely on unofficial Grey Market Premium (GMP) without reading the Red Herring Prospectus.",
      "Failing to distinguish between Fresh Issue (capital for company expansion) and Offer for Sale (promoters cashing out).",
      "Submitting multiple retail applications with the same PAN, leading to automatic rejection by the RTA.",
      "Borrowing high-cost funds or taking unofficial leverage to apply in the HNI category.",
    ],
    faqs: [
      {
        question: "What is ASBA in IPO applications?",
        answer:
          "ASBA (Application Supported by Blocked Amount) is a SEBI-mandated mechanism where your application money remains in your own bank account earning interest, and is only debited if you are allotted shares.",
      },
      {
        question: "How does the allotment process work if an IPO is oversubscribed?",
        answer:
          "In the retail category, if an IPO is oversubscribed, SEBI rules mandate a randomized computerized lottery draw such that all successful applicants receive at least one minimum lot, subject to availability.",
      },
      {
        question: "What is the difference between a Fresh Issue and an Offer for Sale (OFS)?",
        answer:
          "In a Fresh Issue, the company issues new shares and the proceeds go directly to the company for expansion or debt reduction. In an OFS, existing promoters or early investors sell their shares, and the money goes to those selling shareholders.",
      },
      {
        question: "What is Grey Market Premium (GMP)?",
        answer:
          "GMP is an unofficial, unregulated over-the-counter estimate of what buyers are willing to pay for IPO shares before formal exchange listing. It is not approved by SEBI and can be highly volatile or manipulated.",
      },
    ],
    relatedInvestmentSlugs: ["direct-stocks", "index-fund", "mutual-fund-active"],

    // Metadata & Sources
    sourceIds: ["src-sebi-mf-reg", "src-incometax-act"],
    status: "draft",
    lastVerifiedAt: "",
    completenessScore: 85,
    editorialNotes: "Covers mainboard public offerings, ASBA mechanism, and retail bidding dynamics.",
  },

  {
    id: "inv-government-securities",
    slug: "government-securities",
    name: "Central Government Securities (G-Secs / Dated G-Secs)",
    aliases: [
      "G-Secs",
      "Government Bonds",
      "Dated Sovereign Bonds",
      "Gilt Securities",
      "Sovereign Debt",
    ],
    categoryId: "cat-debt-bonds",
    subcategory: "Sovereign Long-Term Debt",
    shortDescription:
      "Long-term sovereign debt instruments issued by the Reserve Bank of India on behalf of the Government of India, offering zero credit default risk and fixed semi-annual coupon payments.",
    beginnerExplanation:
      "When you invest in a G-Sec, you are lending money directly to the Central Government of India. In return, the Government pays you a fixed interest (called a coupon) every six months and returns your entire principal at the end of the term. Because it is backed by the sovereign government, it carries virtually zero credit default risk.",
    mechanismSteps: [
      "The Reserve Bank of India (RBI) conducts primary auctions for Dated Government Securities on behalf of the Central Government to fund national budgetary expenditure.",
      "Individual retail investors bid non-competitively in primary auctions through the RBI Retail Direct portal or stockbrokers.",
      "G-Secs are issued with fixed maturities ranging from 2 years up to 40 years carrying a fixed semi-annual coupon rate.",
      "Interest (coupon) is credited directly into the investor's linked bank account every 6 months until maturity.",
      "On the specified maturity date, the Government of India redeems the security at par value (₹100 face value per unit) into the investor's bank account.",
    ],

    // Financial facts
    returnInfo: {
      returnType: "coupon",
      rateDisplay: "Fixed semi-annual coupon; yield varies based on primary auction cut-off and secondary market trading",
      isGuaranteed: true,
      isIllustrative: false,
      description:
        "Coupon rate is fixed at issuance and paid semi-annually. The sovereign guarantee of the Government of India ensures complete safety of coupon payments and principal redemption at maturity.",
      benchmark: "10-Year Indian Benchmark Sovereign Yield (e.g., 10Y G-Sec Yield)",
      sourceId: "src-rbi-retail-direct",
    },
    minimumAmount: 10000,
    minimumAmountText: "₹10,000 (100 units of ₹100 face value in primary auction via RBI Retail Direct)",
    maximumAmount: 20000000,
    maximumAmountText: "₹2 Crore per auction under non-competitive retail bidding scheme",

    // Risk & Liquidity
    riskLevel: "low",
    riskDescription:
      "Zero credit default risk (sovereign guarantee). However, secondary market prices are subject to interest rate risk if sold prior to maturity.",
    keyRisks: [
      {
        name: "Interest Rate Risk",
        description:
          "If market interest rates rise, existing bond prices fall in the secondary market; long-duration bonds experience higher price swings.",
      },
      {
        name: "Inflation Risk",
        description:
          "Fixed coupon payments may lose real purchasing power if consumer inflation exceeds the bond yield over multi-decade tenures.",
      },
      {
        name: "Secondary Market Liquidity Risk",
        description:
          "Retail lot liquidity in secondary exchange/NDS-OM trading can sometimes have thin bid depth.",
      },
      {
        name: "Reinvestment Risk",
        description:
          "Semi-annual coupon payouts must be reinvested at prevailing future interest rates which could be lower.",
      },
    ],
    liquidityLevel: "moderate",
    liquidityDescription:
      "Can be held to maturity for 100% face value redemption or sold before maturity on the RBI NDS-OM secondary market or stock exchanges.",
    withdrawalRules: [
      "Holding to maturity guarantees 100% full principal redemption directly to linked bank account.",
      "Early exit is possible by selling on the RBI Retail Direct secondary market (NDS-OM) or stock exchange at prevailing secondary market bond prices.",
      "No lock-in penalty from the government, but secondary sale price depends on current market interest rates.",
    ],
    lockInPeriod: "None (tradable in secondary market, though tenures range from 2 to 40 years)",
    suggestedHorizon: "Matches the specific bond maturity tenure (e.g. 5 to 10+ years)",
    volatilityDescription:
      "Zero volatility if held to maturity. Secondary market price fluctuates inversely with benchmark RBI repo rate changes.",

    // Rules & Administration
    eligibility:
      "Resident Indian individuals, HUFs, NRIs (subject to RBI/FEMA regulations), Trusts, Corporates, and institutional entities.",
    eligibleEntities: [
      "Resident Individuals",
      "Non-Resident Indians (NRIs)",
      "Hindu Undivided Families (HUFs)",
      "Sole Proprietorships & Partnerships",
      "Trusts & Corporate Bodies",
    ],
    regulation: "Government Securities Act, 2006 and RBI Retail Direct Guidelines",
    administeringAuthority: "Reserve Bank of India (RBI) / Public Debt Office (PDO)",
    taxationSummary:
      "Coupon interest is added to total income and taxed at your applicable income tax slab rates (no TDS on G-Secs). Capital gains on secondary market transfer: LTCG (>12 months for listed G-Secs) taxed at 12.5% without indexation under Finance Act 2024.",
    taxDetails: {
      investmentStage: "No tax deduction on principal investment amount under Section 80C.",
      growthStage: "Semi-annual coupon payouts are taxed in the financial year of receipt at marginal slab rates.",
      withdrawalStage: "Redemption at par upon maturity has no capital gains tax. Secondary market sales attract STCG (slab rate) or LTCG (12.5% if held >12 months for listed bonds).",
      sectionApplicability: "Sections 56 (Income from Other Sources) and 112 of the Income Tax Act, 1961",
    },

    // Editorial comparisons
    advantages: [
      "Absolute safety of capital and assured cash flow backed by the sovereign Government of India.",
      "Fixed regular income distributed every six months directly to your savings bank account.",
      "Zero account opening and transaction fees when using the RBI Retail Direct platform.",
      "Wide range of available maturities spanning from 2 years up to 40 years to match exact future liabilities.",
      "Can be pledged as collateral for margin trading or bank borrowing.",
    ],
    limitations: [
      "Interest income is fully taxable at your highest marginal income tax slab, making it less tax-efficient for high-bracket earners.",
      "Secondary market prices fluctuate with interest rate changes, risking capital loss if forced to sell early during a rate-hike cycle.",
      "Fixed coupons do not provide inflation-indexed growth.",
      "Lack of compounding unless the investor manually reinvests every semi-annual coupon.",
    ],
    practicalExample: {
      title: "Locking In Guaranteed Retirement Cash Flows via 10-Year G-Sec",
      scenario: "An investor nearing retirement invests ₹5,00,000 in a newly auctioned 10-Year Central Government Bond with a 7.10% annual coupon rate.",
      amountInvested: "₹5,00,000",
      horizon: "10 Years (Hold to maturity)",
      outcomeExplanation:
        "The investor receives ₹17,750 every 6 months (totaling ₹35,500 annually) deposited directly into their bank account for 10 full years. At the end of year 10, the RBI repays the entire ₹5,00,000 principal. Interest is taxed annually at the investor's slab rate.",
      disclaimer:
        "Educational illustration only. Actual yields and cut-offs are determined in competitive RBI auctions. Secondary market bond prices fluctuate with interest rate movements.",
    },
    accessMethods: [
      "RBI Retail Direct Online Portal (Direct G-Sec account with RBI)",
      "Stockbrokers and Demat trading accounts via non-competitive bidding",
      "Gilt Mutual Funds and Target Maturity Index Funds",
    ],
    commonMistakes: [
      "Selling long-tenure G-Secs prematurely during rising interest rate cycles, locking in unnecessary capital losses.",
      "Forgetting that semi-annual interest must be declared in annual income tax filings as 'Income from Other Sources'.",
      "Confusing G-Secs with T-Bills (T-Bills are short-term zero-coupon instruments; G-Secs are long-term coupon-bearing bonds).",
      "Assuming G-Secs are completely illiquid (they can be traded via RBI's NDS-OM platform).",
    ],
    faqs: [
      {
        question: "What is the RBI Retail Direct Scheme?",
        answer:
          "RBI Retail Direct is a one-stop official online portal launched by the Reserve Bank of India allowing individual retail investors to open a Gilt Securities Account (RDG Account) and buy Central Government Bonds, T-Bills, SDLs, and SGBs with zero brokerage charges.",
      },
      {
        question: "Can the Government of India default on G-Sec payments?",
        answer:
          "Central Government securities carry sovereign backing in Indian Rupees, meaning default risk is practically zero as the central sovereign authority controls currency issuance and statutory tax revenues.",
      },
      {
        question: "Is TDS deducted from G-Sec coupon payments?",
        answer:
          "No, there is no Tax Deducted at Source (TDS) on interest paid on Central Government Securities, but the investor must self-declare and pay income tax as per their tax slab.",
      },
      {
        question: "What is the difference between G-Sec coupon and G-Sec yield?",
        answer:
          "The coupon is the fixed annual interest percentage printed on the bond (paid on face value). The yield is the effective annualized return an investor earns based on the actual price paid to purchase the bond in the auction or secondary market.",
      },
    ],
    relatedInvestmentSlugs: ["treasury-bills", "state-development-loans", "corporate-bonds"],

    // Metadata & Sources
    sourceIds: ["src-rbi-retail-direct", "src-incometax-act"],
    status: "draft",
    lastVerifiedAt: "",
    completenessScore: 85,
    editorialNotes: "Covers central government dated securities, primary RBI auctions, and retail participation.",
  },

  {
    id: "inv-treasury-bills",
    slug: "treasury-bills",
    name: "Treasury Bills (T-Bills)",
    aliases: [
      "T-Bills",
      "Central Treasury Bills",
      "91-day T-Bill",
      "182-day T-Bill",
      "364-day T-Bill",
      "Sovereign Money Market",
    ],
    categoryId: "cat-debt-bonds",
    subcategory: "Short-Term Sovereign Money Market",
    shortDescription:
      "Short-term sovereign debt obligations issued by the Government of India at a discount to face value with tenures of 91, 182, or 364 days.",
    beginnerExplanation:
      "Treasury Bills are short-term IOUs issued by the Government of India for durations under one year (91, 182, or 364 days). They do not pay regular interest; instead, you buy them at a discount and the government repays you the full face value at maturity. Because they are central government securities, they carry the highest level of safety.",
    mechanismSteps: [
      "The RBI conducts weekly non-competitive and competitive auctions for 91-day, 182-day, and 364-day Treasury Bills on Wednesdays.",
      "T-Bills are zero-coupon instruments issued at a discount to their face value of ₹100 per unit.",
      "Retail investors place non-competitive bids through RBI Retail Direct or stockbrokers in lots of ₹10,000.",
      "The difference between the discounted issue price and the ₹100 face value represents the investor's implicit return (yield).",
      "On maturity date (91, 182, or 364 days), the RBI automatically credits the full face value (₹100 per unit) to the investor's linked bank account.",
    ],

    // Financial facts
    returnInfo: {
      returnType: "yield",
      rateDisplay: "Discounted yield to maturity (implicit annualized yield based on auction discount)",
      isGuaranteed: true,
      isIllustrative: false,
      description:
        "Zero-coupon structure: Issued at a discount and redeemed at par (₹100). The return is the difference between the discounted purchase price and full face value, guaranteed by the Government of India.",
      benchmark: "91-Day / 364-Day T-Bill Cut-off Yield",
      sourceId: "src-rbi-retail-direct",
    },
    minimumAmount: 10000,
    minimumAmountText: "₹10,000 (100 units of ₹100 face value) and multiples of ₹10,000",
    maximumAmount: 20000000,
    maximumAmountText: "₹2 Crore per weekly auction under non-competitive retail bidding",

    // Risk & Liquidity
    riskLevel: "low",
    riskDescription:
      "Virtually zero credit risk (sovereign guarantee). Minimal interest rate risk due to ultra-short maturity durations.",
    keyRisks: [
      {
        name: "Reinvestment Risk",
        description:
          "Because tenures are short (max 1 year), maturing proceeds must be reinvested at whatever interest rates prevail at that time.",
      },
      {
        name: "Inflation Drag",
        description:
          "Short-term money market yields may be lower than prevailing inflation during low-interest-rate environments.",
      },
      {
        name: "Tax Inefficiency for High Slabs",
        description:
          "Discount gains are treated as short-term capital gains and taxed at your marginal income tax slab rate.",
      },
    ],
    liquidityLevel: "high",
    liquidityDescription:
      "Very high safety and short maturity (up to 364 days). Can be held to maturity or traded in secondary money markets via RBI Retail Direct / NDS-OM.",
    withdrawalRules: [
      "Full maturity proceeds automatically credited to bank account at the end of 91, 182, or 364 days.",
      "Secondary market sale possible before maturity on RBI NDS-OM platform.",
      "No premature penalty charged by RBI; secondary sale price reflects market discount.",
    ],
    lockInPeriod: "None (short maturity of 91, 182, or 364 days)",
    suggestedHorizon: "3 months to 1 year (ideal for short-term liquidity management)",
    volatilityDescription:
      "Extremely low price volatility due to short tenures and absence of intermediate coupon payments.",

    // Rules & Administration
    eligibility:
      "Resident Indian individuals, HUFs, NRIs (subject to RBI/FEMA norms), Trusts, Corporate entities, and institutional participants.",
    eligibleEntities: [
      "Resident Individuals",
      "Non-Resident Indians (NRIs)",
      "Hindu Undivided Families (HUFs)",
      "Corporations & LLPs",
      "Trusts & Educational Institutions",
    ],
    regulation: "Government Securities Act, 2006 / RBI Money Market Guidelines",
    administeringAuthority: "Reserve Bank of India (RBI) on behalf of Government of India",
    taxationSummary:
      "The difference between the issue price and face value (or redemption proceeds) is treated as Short-Term Capital Gains (STCG) and taxed at the investor's applicable marginal income tax slab rate. No TDS applies.",
    taxDetails: {
      investmentStage: "No tax deduction on purchase amount.",
      growthStage: "No interim taxation because T-Bills do not pay periodic coupons.",
      withdrawalStage: "The gain (Redemption Value minus Purchase Price) is taxed as STCG at slab rates in the financial year of maturity.",
      sectionApplicability: "Section 2(42A) and Section 56 of the Income Tax Act, 1961",
    },

    // Editorial comparisons
    advantages: [
      "Backed by the full sovereign faith of the Government of India with zero credit risk.",
      "Zero brokerage and zero account maintenance charges via RBI Retail Direct.",
      "Predictable fixed maturity return over well-defined short horizons (91, 182, or 364 days).",
      "Superior sovereign alternative to short-term bank fixed deposits for corporate and retail cash parking.",
      "No TDS deduction on maturity payout.",
    ],
    limitations: [
      "Does not pay periodic cash flow or coupons; returns are realized only at maturity.",
      "Short tenure requires active reinvestment effort 1 to 4 times a year.",
      "Returns are taxed at peak personal income tax slab rates, making after-tax yields modest for top tax brackets.",
      "Minimum ticket size of ₹10,000 per auction (higher than ₹500 mutual fund SIPs).",
    ],
    practicalExample: {
      title: "Parking Surplus Business Cash in 364-Day T-Bills",
      scenario: "An individual with ₹1,00,000 set aside for an advance tax payment due next year purchases 364-Day T-Bills in an RBI auction at a discounted price of ₹93.50 per unit.",
      amountInvested: "₹93,500 (1,000 units at ₹93.50 discounted issue price)",
      horizon: "364 Days",
      outcomeExplanation:
        "After 364 days, the RBI deposits the full face value of ₹1,00,000 directly into the investor's bank account. The ₹6,500 gain represents an annualized yield of approx 6.95%. The ₹6,500 is taxed as short-term capital gains at the investor's applicable income tax slab rate.",
      disclaimer:
        "Educational illustration only. Exact T-Bill discount rates are determined weekly in RBI competitive auctions based on prevailing money market conditions.",
    },
    accessMethods: [
      "RBI Retail Direct Web Portal",
      "Stockbroker non-competitive bidding screens",
      "Liquid and Overnight Mutual Funds (which invest heavily in T-Bills)",
    ],
    commonMistakes: [
      "Expecting regular monthly or quarterly interest payments (T-Bills pay zero coupons; return is purely discount-based).",
      "Leaving funds idle in a 3% savings account when short-term money could earn sovereign money market yields via T-Bills.",
      "Assuming T-Bills are subject to bank-style TDS (no TDS is deducted, but tax must still be paid in self-assessment).",
    ],
    faqs: [
      {
        question: "What are the three standard tenures for Indian Treasury Bills?",
        answer:
          "The Government of India issues T-Bills in three standard tenures: 91-day, 182-day, and 364-day bills.",
      },
      {
        question: "Why don't T-Bills pay interest coupons?",
        answer:
          "T-Bills are zero-coupon securities. They are issued at a discount to their ₹100 face value and redeemed at full face value at maturity, with the difference acting as your return.",
      },
      {
        question: "Are Treasury Bills safer than Bank Fixed Deposits?",
        answer:
          "Yes, T-Bills carry direct sovereign backing with no ceiling limit, whereas Bank FDs carry insurance up to ₹5 Lakh per depositor per bank via DICGC.",
      },
      {
        question: "How often does the RBI auction T-Bills?",
        answer:
          "The RBI conducts T-Bill primary auctions every week on Wednesday, with settlement taking place on the following working day.",
      },
    ],
    relatedInvestmentSlugs: ["government-securities", "state-development-loans", "corporate-bonds"],

    // Metadata & Sources
    sourceIds: ["src-rbi-retail-direct", "src-incometax-act"],
    status: "draft",
    lastVerifiedAt: "",
    completenessScore: 85,
    editorialNotes: "Covers 91/182/364-day zero-coupon treasury bills and RBI auction bidding.",
  },

  {
    id: "inv-corporate-bonds",
    slug: "corporate-bonds",
    name: "Corporate Bonds & Non-Convertible Debentures (NCDs)",
    aliases: [
      "Corporate Debt",
      "NCDs",
      "Company Debentures",
      "Private Sector Bonds",
      "PSU Bonds",
      "High Yield Bonds",
    ],
    categoryId: "cat-debt-bonds",
    subcategory: "Corporate Credit Fixed Income",
    shortDescription:
      "Debt securities issued by private corporations, Non-Banking Financial Companies (NBFCs), and Public Sector Undertakings (PSUs) offering periodic coupon payments with yields reflecting company credit ratings.",
    beginnerExplanation:
      "When you buy a corporate bond or NCD, you are lending money to a company or financial institution for a fixed period. In exchange, the company pays you regular interest (monthly, quarterly, or annually) and returns your principal at maturity. Because companies can face financial difficulties, they pay higher interest rates than government bonds to compensate for credit risk.",
    mechanismSteps: [
      "Corporates and NBFCs issue Non-Convertible Debentures (NCDs) via public issues or private placement to raise medium-to-long-term debt capital.",
      "SEBI-registered Credit Rating Agencies (CRISIL, ICRA, CARE, India Ratings) assign credit ratings ranging from AAA (highest safety) to D (default).",
      "Investors subscribe to primary NCD issues or buy existing listed bonds on SEBI-regulated Online Bond Platform Providers (OBPPs) or stock exchanges.",
      "The issuer disburses periodic coupon interest payments directly to the investor's registered bank account.",
      "At maturity, the issuer repays the bond's face value, or the investor sells their holding earlier on secondary debt market platforms.",
    ],

    // Financial facts
    returnInfo: {
      returnType: "coupon",
      rateDisplay: "Fixed coupon payout; yield varies with issuer credit rating (AAA, AA, A, etc.)",
      isGuaranteed: false,
      isIllustrative: true,
      description:
        "Contractual interest obligation by the issuing company. Returns are higher than sovereign bonds to compensate for credit risk. Capital safety depends on the financial solvency and creditworthiness of the issuing entity.",
      benchmark: "CRISIL Corporate Bond Index / 10-Year AAA Corporate Yield",
      sourceId: "src-sebi-mf-reg",
    },
    minimumAmount: 10000,
    minimumAmountText: "₹10,000 for public NCD issues; ₹10,000 to ₹1,00,000 on SEBI-registered Online Bond Platforms (reduced from ₹1 Lakh by SEBI in 2024)",
    maximumAmount: null,
    maximumAmountText: "No statutory maximum limit",

    // Risk & Liquidity
    riskLevel: "moderate",
    riskDescription:
      "Carries credit/default risk, rating downgrade risk, interest rate risk, and liquidity risk. Lower-rated bonds (AA and below) carry moderate to high risk.",
    keyRisks: [
      {
        name: "Credit & Default Risk",
        description:
          "The issuing company may face insolvency, operational failure, or cash flow distress, defaulting on interest or principal repayments.",
      },
      {
        name: "Rating Downgrade Risk",
        description:
          "If rating agencies downgrade the bond (e.g., from AAA to AA), secondary market bond prices drop immediately.",
      },
      {
        name: "Liquidity Risk",
        description:
          "Secondary market trading volumes in corporate bonds can be thin, making early exit before maturity difficult or costly.",
      },
      {
        name: "Call / Prepayment Risk",
        description:
          "Issuers may exercise call options to redeem high-interest bonds early when prevailing interest rates decline.",
      },
    ],
    liquidityLevel: "moderate",
    liquidityDescription:
      "Tradable on exchange debt segments and SEBI-regulated Online Bond Platform Providers (OBPPs), but retail lot liquidity varies significantly by issuer.",
    withdrawalRules: [
      "Holders receive periodic interest and principal redemption automatically at maturity.",
      "Early exit is achieved by selling units on stock exchange debt segments or authorized OBPP portals.",
      "Secured NCDs carry a charge on company assets, providing structural recovery priority over unsecured creditors in bankruptcy.",
    ],
    lockInPeriod: "None (tradable in secondary market; defined bond tenures typically 1 to 10 years)",
    suggestedHorizon: "Matches bond maturity (typically 2 to 5 years)",
    volatilityDescription:
      "Moderate volatility influenced by benchmark interest rate shifts, credit spread widening, and issuer-specific news.",

    // Rules & Administration
    eligibility:
      "Resident Indian individuals, HUFs, NRIs (subject to issuer terms and FEMA limits), Corporates, Trusts, and institutional investors.",
    eligibleEntities: [
      "Resident Individuals",
      "Non-Resident Indians (NRIs)",
      "Hindu Undivided Families (HUFs)",
      "Corporate Entities & LLPs",
      "Trusts & Family Offices",
    ],
    regulation: "SEBI (Issue and Listing of Non-Convertible Securities) Regulations, 2021",
    administeringAuthority: "Securities and Exchange Board of India (SEBI) / Debenture Trustees",
    taxationSummary:
      "Coupon interest is added to total income and taxed at your applicable income tax slab rates (10% TDS applies on listed corporate bonds under Section 193). Listed bond capital gains: LTCG (>12 months) taxed at 12.5% without indexation under Finance Act 2024; STCG taxed at slab rates.",
    taxDetails: {
      investmentStage: "No tax deduction on investment amount.",
      growthStage: "Coupon interest is taxable annually at marginal slab rates in the year of receipt.",
      withdrawalStage: "Redemption at par has no capital gain. Secondary sales attract STCG (slab rate) or LTCG (12.5% if held >12 months for listed bonds).",
      sectionApplicability: "Sections 193 (TDS on Debentures), 56, and 112 of the Income Tax Act, 1961",
    },

    // Editorial comparisons
    advantages: [
      "Yields are typically 100 to 300 basis points higher than comparable government securities or bank fixed deposits.",
      "Predictable fixed income cash flows with monthly, quarterly, or annual coupon payout options.",
      "Secured NCDs provide legal recourse and asset backing through an independent SEBI-registered Debenture Trustee.",
      "SEBI regulations now allow lower minimum investment thresholds (₹10,000) on Online Bond Platforms.",
      "Portfolio diversification away from equity market volatility.",
    ],
    limitations: [
      "Credit risk: Unlike government bonds, corporate issuers can and have defaulted on debenture obligations.",
      "Interest is fully taxable at marginal slab rates, significantly reducing net yields for investors in the 30% tax bracket.",
      "Secondary market liquidity remains fragmented and lower than equity markets.",
      "Credit ratings can change rapidly during macroeconomic stress or company governance crises.",
    ],
    practicalExample: {
      title: "Investing in a Senior Secured AAA-Rated Corporate NCD",
      scenario: "An investor seeking regular semi-annual income allocates ₹1,00,000 into a 3-year Senior Secured AAA-rated PSU/Corporate bond paying an 8.20% annual coupon.",
      amountInvested: "₹1,00,000",
      horizon: "3 Years",
      outcomeExplanation:
        "The investor receives ₹4,100 every six months (₹8,200 annually). At the end of year 3, the company redeems the principal of ₹1,00,000. TDS of 10% is deducted on interest payouts and adjusted against final income tax liability.",
      disclaimer:
        "Educational illustration only. Corporate bonds carry credit and default risks. Credit ratings are subject to periodic review and change by rating agencies.",
    },
    accessMethods: [
      "SEBI-regulated Online Bond Platform Providers (OBPPs like Wint Wealth, Grip Invest, GoldenPi, BondsIndia)",
      "Direct subscription during Public NCD issues via stockbrokers",
      "Stock exchange secondary debt market segments (NSE/BSE)",
      "Corporate Bond Mutual Funds & Target Maturity Funds",
    ],
    commonMistakes: [
      "Chasing unrated or high-yield BBB-rated bonds offering 12-14% interest without understanding the high probability of default.",
      "Confusing subordinated or perpetual bonds (like AT1 bonds) with senior secured NCDs.",
      "Ignoring the financial health, cash flows, and debt-to-equity ratio of the issuing company.",
      "Assuming that a high credit rating is a permanent guarantee against future default.",
    ],
    faqs: [
      {
        question: "What is the difference between a Secured and Unsecured NCD?",
        answer:
          "A Secured NCD is backed by specific company assets or receivables, meaning if the company defaults, the debenture trustee can liquidate those assets to recover investor funds. An Unsecured NCD is backed only by the company's general creditworthiness with no specific asset charge.",
      },
      {
        question: "What are Credit Ratings in Corporate Bonds?",
        answer:
          "Credit ratings (like AAA, AA+, AA, A, BBB) evaluate the issuer's financial strength and ability to service debt on time. AAA represents the highest safety with lowest default probability, while lower ratings indicate progressively higher credit risk and higher yields.",
      },
      {
        question: "What role does a Debenture Trustee play?",
        answer:
          "A SEBI-registered Debenture Trustee is appointed to safeguard the interests of bondholders, monitor company asset security cover, track coupon disbursements, and initiate legal recovery in case of default.",
      },
      {
        question: "Is TDS deducted on Corporate Bond interest?",
        answer:
          "Yes, under Section 193 of the Income Tax Act, TDS at 10% is deducted from interest payments on listed corporate bonds if the interest exceeds statutory limits, which can be claimed as tax credit in your ITR.",
      },
    ],
    relatedInvestmentSlugs: ["government-securities", "state-development-loans", "treasury-bills"],

    // Metadata & Sources
    sourceIds: ["src-sebi-mf-reg", "src-incometax-act"],
    status: "draft",
    lastVerifiedAt: "",
    completenessScore: 85,
    editorialNotes: "Covers senior secured NCDs, credit rating scales, and OBPP investment avenues.",
  },

  {
    id: "inv-state-development-loans",
    slug: "state-development-loans",
    name: "State Development Loans (SDLs)",
    aliases: [
      "SDLs",
      "State Government Bonds",
      "State Sovereign Debt",
      "State G-Secs",
    ],
    categoryId: "cat-debt-bonds",
    subcategory: "Sub-Sovereign Debt",
    shortDescription:
      "Bonds issued by State Governments in India through RBI auctions to fund state infrastructure and socio-economic development projects, offering sovereign-like safety with yields slightly higher than Central G-Secs.",
    beginnerExplanation:
      "State Development Loans (SDLs) are bonds issued by individual Indian state governments (like Maharashtra, Tamil Nadu, or Gujarat) to borrow money for public infrastructure. The Reserve Bank of India manages these auctions and handles all interest and principal payouts. They offer safety nearly identical to Central Government bonds but usually pay a slightly higher interest rate.",
    mechanismSteps: [
      "State Governments formulate borrowing limits approved under Article 293(3) of the Constitution of India in consultation with the Ministry of Finance.",
      "The Reserve Bank of India (RBI) conducts bi-weekly primary auctions for State Development Loans on behalf of participating state governments.",
      "Retail investors bid non-competitively through the RBI Retail Direct portal or registered stockbrokers.",
      "Fixed semi-annual coupons are credited directly into the investor's bank account via the RBI's automated debt servicing mechanism.",
      "The RBI has an automatic debit mechanism on central tax devolution allocations to ensure state bond servicing is prioritized, and redeems the bond at par value (₹100) at maturity.",
    ],

    // Financial facts
    returnInfo: {
      returnType: "coupon",
      rateDisplay: "Fixed semi-annual coupon; yield typically 25 to 60 basis points higher than Central G-Secs",
      isGuaranteed: true,
      isIllustrative: false,
      description:
        "Semi-annual fixed coupon. Backed by state finances with an institutional debt servicing mechanism administered by the Reserve Bank of India, ensuring virtually zero default experience.",
      benchmark: "10-Year Central G-Sec Yield + State Spread (typically 25-50 bps spread)",
      sourceId: "src-rbi-retail-direct",
    },
    minimumAmount: 10000,
    minimumAmountText: "₹10,000 (100 units of ₹100 face value) and multiples thereof",
    maximumAmount: 20000000,
    maximumAmountText: "₹2 Crore per auction under non-competitive retail bidding",

    // Risk & Liquidity
    riskLevel: "low",
    riskDescription:
      "Extremely low credit risk due to RBI debt servicing oversight and intercept mechanisms on central revenue transfers. Secondary prices carry interest rate risk.",
    keyRisks: [
      {
        name: "Interest Rate Risk",
        description:
          "Bonds with long maturities (10 to 15 years) experience price drops in the secondary market if market interest rates rise.",
      },
      {
        name: "State Fiscal Variance",
        description:
          "Different states carry varying debt-to-GSDP ratios and fiscal deficits, leading to yield spreads across states.",
      },
      {
        name: "Secondary Market Liquidity",
        description:
          "Retail lot trading on stock exchanges is less active than Central Government benchmark bonds.",
      },
      {
        name: "Inflation Risk",
        description:
          "Fixed coupon rates do not adjust upward if long-term inflation surges.",
      },
    ],
    liquidityLevel: "moderate",
    liquidityDescription:
      "Can be held to maturity for 100% principal repayment or sold on the RBI Retail Direct secondary market (NDS-OM) and stock exchanges.",
    withdrawalRules: [
      "Full face value principal is credited to the investor's bank account automatically on the maturity date.",
      "Early exit is possible by selling units on the RBI NDS-OM platform or exchange debt segment at prevailing market prices.",
      "No premature penalty charged by RBI; price realized reflects prevailing secondary market yields.",
    ],
    lockInPeriod: "None (tradable in secondary markets; issued tenures typically 5 to 15 years)",
    suggestedHorizon: "5 to 10+ years (aligned with the specific bond maturity date)",
    volatilityDescription:
      "Zero volatility if held to maturity. Secondary market prices move inversely with RBI interest rate benchmarks.",

    // Rules & Administration
    eligibility:
      "Resident Indian individuals, HUFs, NRIs (subject to FEMA guidelines), Trusts, Corporates, and institutional debt funds.",
    eligibleEntities: [
      "Resident Individuals",
      "Non-Resident Indians (NRIs)",
      "Hindu Undivided Families (HUFs)",
      "Charitable & Religious Trusts",
      "Corporate Bodies & Banks",
    ],
    regulation: "Government Securities Act, 2006 / RBI State Debt Regulations",
    administeringAuthority: "Reserve Bank of India (RBI) / Respective State Governments",
    taxationSummary:
      "Coupon payments are added to total annual taxable income and taxed at marginal income tax slab rates (no TDS). Secondary market capital gains: LTCG (>12 months for listed SDLs) taxed at 12.5% without indexation under Finance Act 2024.",
    taxDetails: {
      investmentStage: "No tax deduction on principal investment under Section 80C.",
      growthStage: "Semi-annual coupon receipts are taxable as income from other sources in the year received.",
      withdrawalStage: "Redemption at par at maturity incurs no capital gain tax. Secondary market transfers attract STCG (slab rate) or LTCG (12.5% if held >12 months for listed bonds).",
      sectionApplicability: "Sections 56 and 112 of the Income Tax Act, 1961",
    },

    // Editorial comparisons
    advantages: [
      "Higher yields (typically 25-60 bps higher) than Central Government bonds with practically identical sovereign safety.",
      "Institutional safety net: RBI manages debt servicing and holds statutory power to debit central devolutions to pay bondholders.",
      "Zero brokerage, custody, or transaction fees when investing directly through the RBI Retail Direct platform.",
      "Direct regular semi-annual interest credited into your bank account for long-term income planning.",
      "Qualifies as Statutory Liquidity Ratio (SLR) security for financial institutions, ensuring steady institutional demand.",
    ],
    limitations: [
      "Coupon interest is fully taxable at your highest applicable income tax slab rate.",
      "Lower secondary market liquidity for retail investors compared to Central G-Sec benchmark bonds.",
      "Bond tenures are typically long (often 10 years), requiring a long-term capital commitment if holding to maturity.",
      "No automatic compounding; reinvesting semi-annual payouts requires manual investor intervention.",
    ],
    practicalExample: {
      title: "Earning Higher Sovereign Yields with a 10-Year Tamil Nadu or Gujarat SDL",
      scenario: "An investor seeking guaranteed long-term cash flow invests ₹5,00,000 in a 10-Year State Development Loan yielding 7.50% (35 bps above the 7.15% Central G-Sec).",
      amountInvested: "₹5,00,000",
      horizon: "10 Years",
      outcomeExplanation:
        "The investor receives ₹18,750 every six months (₹37,500 annually) directly in their bank account for 10 years. At year 10, the RBI transfers the ₹5,00,000 principal back to the investor. Over 10 years, the extra 35 bps yield provides ₹17,500 in additional cumulative interest over a central G-sec.",
      disclaimer:
        "Educational illustration only. SDL auction yields vary across states and auction dates depending on state fiscal dynamics and investor demand.",
    },
    accessMethods: [
      "RBI Retail Direct Online Portal (non-competitive bidding)",
      "Stockbroking platforms via non-competitive primary auction bidding",
      "Target Maturity Debt Mutual Funds & SDL Index Funds",
    ],
    commonMistakes: [
      "Assuming State Government bonds carry high default risk like private corporate bonds (RBI manages the debt servicing with central revenue deduction safeguards).",
      "Overlooking the yield spread between different states (some states offer higher yields due to local borrowing size).",
      "Selling prematurely during interest rate spike cycles rather than holding to maturity.",
    ],
    faqs: [
      {
        question: "How safe are State Development Loans (SDLs) compared to Central G-Secs?",
        answer:
          "SDLs are considered sovereign-equivalent instruments. The RBI manages the debt servicing, and agreements empower the RBI to deduct debt service obligations from the state's share of central tax devolutions before distributing funds to the state.",
      },
      {
        question: "Why do SDLs offer higher interest rates than Central Government Securities?",
        answer:
          "SDLs trade at a spread (typically 25 to 60 basis points higher) over Central G-Secs due to slightly lower secondary market liquidity and variations in individual state fiscal debt levels.",
      },
      {
        question: "Can NRIs invest in State Development Loans?",
        answer:
          "Yes, Non-Resident Indians (NRIs) can invest in SDLs through the RBI Retail Direct scheme or through eligible stockbroker accounts under RBI/FEMA regulations.",
      },
      {
        question: "Do SDLs deduct TDS on coupon payouts?",
        answer:
          "No, there is no TDS on interest paid on State Development Loans. Investors must declare coupon earnings in their annual income tax returns under Income from Other Sources.",
      },
    ],
    relatedInvestmentSlugs: ["government-securities", "treasury-bills", "corporate-bonds"],

    // Metadata & Sources
    sourceIds: ["src-rbi-retail-direct", "src-incometax-act"],
    status: "draft",
    lastVerifiedAt: "",
    completenessScore: 85,
    editorialNotes: "Covers state government debt auctions, RBI Retail Direct access, and state yield spreads.",
  },
];
